### PR TITLE
Backport https://reviews.llvm.org/D134641

### PR DESCRIPTION
**Pull request by pxl-th**
This fixes https://github.com/JuliaGPU/AMDGPU.jl/issues/518 which appeared with Navi 3 as a target.

### CODE REVIEW

**Comment by vchuravy** [comment]
Can you fix up the authorship information, and refer the commit you cherry-picked in the commit message?

I normally use `git cherry-pick -x`

**Comment by vchuravy** [comment]
Thanks! And to confirm this is only needed on LLVM 15, and not LLVM 16?

**Comment by pxl-th** [comment]
Yes, this fix is already in LLVM 16.

**Comment by vchuravy** [comment]
x-ref https://github.com/JuliaPackaging/Yggdrasil/pull/7551

**Pull request merged**
