### PR TITLE
Add support for unwinding during prologue/epilogue

### PR DESCRIPTION
**Pull request by giordano**
Ref: https://github.com/JuliaLang/julia/issues/44499.  CC: @Keno @vchuravy @fxcoudert

### CODE REVIEW

**Comment by fxcoudert** [comment]
I don't fully understand the Julia build system, but: how do I apply that during build, and how does it fix the current issue of missing patch file during build?

**Comment by giordano** [comment]
When building llvm from source in Julia, this repository is what is used by default, with the branch/ref specified by https://github.com/JuliaLang/julia/blob/6026b5ff2a8035fc9d70af30123af9a6e722c585/deps/llvm.version (hence why I opened this pull request to target the branch `julia-13.0.1-0`)

**Comment by vchuravy** [comment]
https://github.com/JuliaPackaging/Yggdrasil/pull/4853

**Comment by vchuravy** [comment]
@Keno Is there a phabricator change open for this PR? If not can you create one

**Comment by giordano** [comment]
Note that we we apply this patch directly to libunwind: https://github.com/JuliaPackaging/Yggdrasil/blob/cc0b0caa2df2857cc9c00527732cb79c97ed35a1/L/LLVMLibUnwind/LLVMLibUnwind%4012.0.1/bundled/patches/0001-unwind-prologue-epilogue.patch.  I'm not sure we need to rebuild llvm just for that?

**Comment by vchuravy** [comment]
I don't understand why we have a separate LLVMLibUnwind to begin with. It should be part of the monobuild.

**Comment by giordano** [comment]
Don't ask me, I'm merely reporting how it is :stuck_out_tongue_winking_eye:

**Comment by fxcoudert** [comment]
The issue in https://github.com/JuliaLang/julia/issues/44499 is that several patch files (3 IIRC) are missing from the Julia source tree, while being referred to in the Julia build system ([julia/deps/unwind.mk](https://github.com/JuliaLang/julia/blob/811e534ca7398b4856149938995539f77078939d/deps/unwind.mk#L91))

This PR is modifying a header file in libunwind. I'm not seeing how merging this fixes the issue. I'm totally confused.

**Comment by giordano** [comment]
Yes, I'm also confused.  I misread where the patch was being applied, I was convinced it was in `llvm.mk`, instead it was in `unwind.mk`.

Upstreaming the patch, if possible, would solve all issues in the long term though :slightly_smiling_face:

**Pull request merged**
