### PR TITLE
Apply  [PATCH] [clang-repl] Add a interpreter-specific overload of op…

### PR DESCRIPTION
**Pull request by Gnimuc**
…erator  new for C++.

### CODE REVIEW

**Comment by giordano** [comment]
I pushed https://github.com/JuliaLang/llvm-project/commit/0007e48608221f440dce2ea0d3e4f561fc10d3c6 which (a) retains authorship, (b) preserves full commit message, (c) references the upstream commit (I did a cherry-pick, instead of manually applying a patch).

**Comment by Gnimuc** [comment]
Thanks! Could you also bump JLLs for LLVM 17 in Ygg?

**Comment by giordano** [comment]
@Gnimuc I think we need also https://github.com/llvm/llvm-project/pull/78843?  ***Edit***: maybe not, that's an internal test in llvm

**Comment by giordano** [comment]
> Thanks! Could you also bump JLLs for LLVM 17 in Ygg?

That you can do yourself, I created the tag [`julia-17.0.6-5`](https://github.com/JuliaLang/llvm-project/releases/tag/julia-17.0.6-5).  take a look at https://github.com/JuliaPackaging/Yggdrasil/pull/8697, https://github.com/JuliaPackaging/Yggdrasil/pull/8705, https://github.com/JuliaPackaging/Yggdrasil/pull/8715.  The PRs have to be opened in that order, after the previous one was merged, and the corresponding PRs in General have been merged.

**Comment by Gnimuc** [comment]
CppInterOp only needs [this patch](https://github.com/compiler-research/CppInterOp/tree/main/patches/llvm) for llvm 17 at the moment.

**Pull request closed without merging**
