### PR TITLE
Fix 'Rebase [ittapi] Check out branch only if ITTAPI is cloned'

### PR DESCRIPTION
**Pull request by Zentrik**
Tested yggy and Julia build with this.

### CODE REVIEW

**Comment by giordano** [comment]
Do you mind if I take these commits and squash them with https://github.com/JuliaLang/llvm-project/commit/8b3aad308873bdd78b6fc7f5ee362137614ee0aa and https://github.com/JuliaLang/llvm-project/commit/8e565932e655767f93e45aa71887d1f633d1aa6e?  I prefer to keep history as simple as possible :slightly_smiling_face:

Side note, any hope to upstream any of this?

**Comment by Zentrik** [comment]
Go ahead. I can create a pr upstreaming but not sure if it will be accepted given it would break stuff.

**Comment by Zentrik** [comment]
Actually https://github.com/JuliaLang/llvm-project/commit/8e565932e655767f93e45aa71887d1f633d1aa6e is a separate upstream pr fixing a bug. Though, if you want to squash it too go ahead.

**Comment by giordano** [comment]
Ok, I'll leave https://github.com/JuliaLang/llvm-project/commit/8e565932e655767f93e45aa71887d1f633d1aa6e out, no problem

**Comment by giordano** [comment]
Done!  The tip of the [branch](https://github.com/JuliaLang/llvm-project/tree/julia-release/19.x) is now dae03206c1f4dcf812ff27e2860358ccb933856c

**Pull request closed without merging**
